classdef SimscapeWrapperSystem < matlab.System & coder.ExternalDependency
    % SimscapeWrapperSystem wraps generated C++ Simscape code.
    
    properties (Access = private)
        % Define internal properties or object pointers if necessary
    end
    
    methods (Access = protected)
        function setupImpl(obj)
            % Initialize the generated C++ model
            if coder.target('MATLAB')
                % Simulation behavior if run in normal MATLAB mode
            else
                % Call the C++ initialization function generated by Simulink Coder
                coder.ceval('Testing_initialize');
            end
        end
        
        function y = stepImpl(obj, u)
            % Execute one integration step
            y = zeros(1,1); % Preallocate output based on model dimensions
            
            if coder.target('MATLAB')
                % Simulation behavior
            else
                % Assign input to the generated external structure
                coder.ceval('Set_Model_Inputs', u);
                
                % Call the generated C++ step function: x(k+1) = f(x(k), u(k))
                coder.ceval('Testing_step');
                
                % Retrieve the output
                y = coder.ceval('Get_Model_Outputs');
            end
        end
        
        function releaseImpl(obj)
            % Terminate and clean up
            if ~coder.target('MATLAB')
                coder.ceval('Testing_terminate');
            end
        end
    end
    
    methods (Static)
        function name = getDescriptiveName()
            name = 'SimscapeWrapperSystem';
        end
        
        function b = isSupportedContext(context)
            b = context.isMatlabHostTarget();
        end
        
        function updateBuildInfo(buildInfo, context)
            % Link the generated standalone C++ code to the System Object
            srcDir = fullfile(pwd, 'ModelName_ert_rtw');
            
            % Add include paths
            addIncludePaths(buildInfo, srcDir);
            
            % Add generated source files
            addSourceFiles(buildInfo, 'Testing.cpp', srcDir);
            addSourceFiles(buildInfo, 'Testing_data.cpp', srcDir);
        end
    end
end